stages:
  download_data:
    cmd: python3 download_data.py
    deps:
    - download_data.py
    outs:
    - datasets/cifar10
  train:
    cmd: python3 train.py
    deps:
    - datasets/cifar10
    - train.py
    - net.py
    params:
    - dataset.batch_size
    - hyperparams.num_epochs
    metrics:
    - metrics.json
    outs:
    - checkpoints
